"""Wipe the database and reseed only what's needed for the system to work.

Keeps:
  - the admin user (so you can log in)
  - the 5 fare-setting rows (so the fare engine works)

Deletes everything else. After this, the admin portal shows real-time data
generated by your users (mobile app signups, bookings, etc.) — no demo data.

Run:
    python reset_db.py
"""
import asyncio
import os

from app.database import engine, Base, AsyncSessionLocal
from app import models  # noqa: F401
from seed import seed_admin, seed_fare_settings


async def main():
    # Drop the SQLite file if present
    db_path = "ziggo.db"
    if os.path.exists(db_path):
        os.remove(db_path)
        print(f"[reset_db] Removed {db_path}")

    # Recreate schema
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    print("[reset_db] Tables recreated.")

    # Reseed ONLY admin + fare settings
    async with AsyncSessionLocal() as db:
        await seed_admin(db)
        await seed_fare_settings(db)
        await db.commit()

    print("[reset_db] Done. DB now contains:")
    print("  - 1 admin user (+94700000000 / admin123)")
    print("  - 5 fare settings (bike, tuk, car, van, truck)")
    print("  - 0 customers, 0 drivers, 0 bookings, 0 restaurants, 0 promos")
    print("")
    print("Open http://localhost:8000/admin/login to see the empty admin portal.")
    print("Any data from here on is REAL — generated by app users.")


if __name__ == "__main__":
    asyncio.run(main())
