"""add_market_vendor_details

Revision ID: 1f3155afef0d
Revises: b2f1a9c4d7e3
Create Date: 2026-06-09 09:03:04.562054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1f3155afef0d'
down_revision: Union[str, None] = 'b2f1a9c4d7e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_messages_id'), table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_index(op.f('ix_driver_applications_id'), table_name='driver_applications')
    op.drop_table('driver_applications')
    op.add_column('market_vendors', sa.Column('business_registration_number', sa.String(length=100), nullable=True))
    op.add_column('market_vendors', sa.Column('tax_vat_number', sa.String(length=100), nullable=True))
    op.add_column('market_vendors', sa.Column('self_delivery', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('market_vendors', sa.Column('marketplace_delivery', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('market_vendors', sa.Column('delivery_radius_km', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('market_vendors', sa.Column('average_prep_time_minutes', sa.Integer(), nullable=True))
    op.add_column('market_vendors', sa.Column('bank_name', sa.String(length=100), nullable=True))
    op.add_column('market_vendors', sa.Column('account_holder_name', sa.String(length=100), nullable=True))
    op.add_column('market_vendors', sa.Column('account_number', sa.String(length=100), nullable=True))
    op.add_column('market_vendors', sa.Column('branch_name', sa.String(length=100), nullable=True))
    op.add_column('market_vendors', sa.Column('nic_passport_copy_url', sa.String(length=255), nullable=True))
    op.add_column('market_vendors', sa.Column('business_reg_cert_url', sa.String(length=255), nullable=True))
    op.add_column('market_vendors', sa.Column('tax_cert_url', sa.String(length=255), nullable=True))
    op.add_column('market_vendors', sa.Column('food_license_url', sa.String(length=255), nullable=True))
    op.add_column('market_vendors', sa.Column('additional_docs_url', sa.String(length=255), nullable=True))
    op.add_column('market_vendors', sa.Column('commission_percentage', sa.DECIMAL(precision=5, scale=2), server_default='10.00', nullable=False))
    op.add_column('market_vendors', sa.Column('priority_level', sa.String(length=50), server_default='standard', nullable=False))
    op.add_column('market_vendors', sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_vendors', 'is_featured')
    op.drop_column('market_vendors', 'priority_level')
    op.drop_column('market_vendors', 'commission_percentage')
    op.drop_column('market_vendors', 'additional_docs_url')
    op.drop_column('market_vendors', 'food_license_url')
    op.drop_column('market_vendors', 'tax_cert_url')
    op.drop_column('market_vendors', 'business_reg_cert_url')
    op.drop_column('market_vendors', 'nic_passport_copy_url')
    op.drop_column('market_vendors', 'branch_name')
    op.drop_column('market_vendors', 'account_number')
    op.drop_column('market_vendors', 'account_holder_name')
    op.drop_column('market_vendors', 'bank_name')
    op.drop_column('market_vendors', 'average_prep_time_minutes')
    op.drop_column('market_vendors', 'delivery_radius_km')
    op.drop_column('market_vendors', 'marketplace_delivery')
    op.drop_column('market_vendors', 'self_delivery')
    op.drop_column('market_vendors', 'tax_vat_number')
    op.drop_column('market_vendors', 'business_registration_number')
    op.create_table('driver_applications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('mobile', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('vehicle_type', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('nic', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('driver_applications_pkey'))
    )
    op.create_index(op.f('ix_driver_applications_id'), 'driver_applications', ['id'], unique=False)
    op.create_table('contact_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('contact_messages_pkey'))
    )
    op.create_index(op.f('ix_contact_messages_id'), 'contact_messages', ['id'], unique=False)
    # ### end Alembic commands ###
