"""Add driver_search_radius_km to SystemSettings

Revision ID: 7c5c836235d7
Revises: 7f3e8c9f1fc6
Create Date: 2026-06-30 16:48:22.801327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7c5c836235d7'
down_revision: Union[str, None] = '7f3e8c9f1fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('driver_search_radius_km', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'driver_search_radius_km')
    # ### end Alembic commands ###
