"""Add peak_surcharge to Booking

Revision ID: 7f3e8c9f1fc6
Revises: 5d812e5c8e3a
Create Date: 2026-06-30 13:26:56.754966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f3e8c9f1fc6'
down_revision: Union[str, None] = '5d812e5c8e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surge_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('coordinates', sa.JSON(), nullable=False),
    sa.Column('flat_extra_charge', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('end_time', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=7), server_default='#dc3545', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surge_zones_id'), 'surge_zones', ['id'], unique=False)
    op.add_column('bookings', sa.Column('peak_surcharge', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.alter_column('bookings', 'driver_accepted_lat',
               existing_type=sa.DECIMAL(precision=10, scale=6),
               type_=sa.DECIMAL(precision=10, scale=7),
               existing_nullable=True)
    op.alter_column('bookings', 'driver_accepted_lng',
               existing_type=sa.DECIMAL(precision=10, scale=6),
               type_=sa.DECIMAL(precision=10, scale=7),
               existing_nullable=True)
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'drivers', ['driver_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'bookings', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.add_column('fare_settings', sa.Column('promo_message', sa.String(length=255), nullable=True))
    op.add_column('fare_settings', sa.Column('discount_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('fare_settings', sa.Column('display_order', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'food_orders', type_='foreignkey')
    op.drop_constraint(None, 'food_orders', type_='foreignkey')
    op.drop_constraint(None, 'food_orders', type_='foreignkey')
    op.create_foreign_key(None, 'food_orders', 'restaurants', ['restaurant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'food_orders', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'food_orders', 'drivers', ['driver_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'bookings', ['booking_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'payments', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'restaurants', type_='foreignkey')
    op.create_foreign_key(None, 'restaurants', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.alter_column('system_settings', 'cancellation_grace_period_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('system_settings', 'password_reset_option',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'email'"))
    op.alter_column('system_settings', 'max_settle_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('(1000)'))
    op.add_column('users', sa.Column('referral_code', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('referred_by_user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['referral_code'])
    op.create_foreign_key(None, 'users', 'users', ['referred_by_user_id'], ['id'])
    op.drop_column('users', 'language')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'emergency_contact_number')
    op.drop_column('users', 'emergency_contact_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emergency_contact_name', sa.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_number', sa.VARCHAR(length=20), nullable=True))
    op.add_column('users', sa.Column('gender', sa.VARCHAR(length=20), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.DATE(), nullable=True))
    op.add_column('users', sa.Column('language', sa.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'referred_by_user_id')
    op.drop_column('users', 'referral_code')
    op.alter_column('system_settings', 'max_settle_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('(1000)'))
    op.alter_column('system_settings', 'password_reset_option',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'email'"))
    op.alter_column('system_settings', 'cancellation_grace_period_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.drop_constraint(None, 'restaurants', type_='foreignkey')
    op.create_foreign_key(None, 'restaurants', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'bookings', ['booking_id'], ['id'])
    op.drop_constraint(None, 'food_orders', type_='foreignkey')
    op.drop_constraint(None, 'food_orders', type_='foreignkey')
    op.drop_constraint(None, 'food_orders', type_='foreignkey')
    op.create_foreign_key(None, 'food_orders', 'restaurants', ['restaurant_id'], ['id'])
    op.create_foreign_key(None, 'food_orders', 'drivers', ['driver_id'], ['id'])
    op.create_foreign_key(None, 'food_orders', 'customers', ['customer_id'], ['id'])
    op.drop_column('fare_settings', 'display_order')
    op.drop_column('fare_settings', 'discount_percentage')
    op.drop_column('fare_settings', 'promo_message')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'drivers', ['driver_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'customers', ['customer_id'], ['id'])
    op.alter_column('bookings', 'driver_accepted_lng',
               existing_type=sa.DECIMAL(precision=10, scale=7),
               type_=sa.DECIMAL(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('bookings', 'driver_accepted_lat',
               existing_type=sa.DECIMAL(precision=10, scale=7),
               type_=sa.DECIMAL(precision=10, scale=6),
               existing_nullable=True)
    op.drop_column('bookings', 'peak_surcharge')
    op.drop_index(op.f('ix_surge_zones_id'), table_name='surge_zones')
    op.drop_table('surge_zones')
    # ### end Alembic commands ###
