"""add_peak_hour_fields

Revision ID: 8b082f8d60cd
Revises: 2a7c9e4b1d05
Create Date: 2026-06-15 11:02:10.715382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8b082f8d60cd'
down_revision: Union[str, None] = '2a7c9e4b1d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('peak_start_hour', sa.Integer(), nullable=True))
    op.add_column('system_settings', sa.Column('peak_end_hour', sa.Integer(), nullable=True))
    op.add_column('system_settings', sa.Column('peak_extra_amount', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('system_settings', sa.Column('peak_is_active', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'peak_is_active')
    op.drop_column('system_settings', 'peak_extra_amount')
    op.drop_column('system_settings', 'peak_end_hour')
    op.drop_column('system_settings', 'peak_start_hour')
    # ### end Alembic commands ###
