"""Add PickMe profile fields

Revision ID: e104da0c7531
Revises: 
Create Date: 2026-06-08 09:19:15.719383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e104da0c7531'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # removed bookings alter
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('emergency_contact_number')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('language')
        batch_op.drop_column('gender')
        batch_op.drop_column('birthday')

    # removed bookings downgrade
    # ### end Alembic commands ###
