"""add_referral_amounts_to_settings

Revision ID: edeb844a1e65
Revises: 9f241f06dd78
Create Date: 2026-07-09 15:51:38.438414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'edeb844a1e65'
down_revision: Union[str, None] = '9f241f06dd78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('referral_referrer_amount', sa.Numeric(10, 2), nullable=False, server_default='300.00'))
    op.add_column('system_settings', sa.Column('referral_referred_amount', sa.Numeric(10, 2), nullable=False, server_default='300.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'referral_referrer_amount')
    op.drop_column('system_settings', 'referral_referred_amount')
    # ### end Alembic commands ###
