"""Add is_truck to FareSetting

Revision ID: f857908b9499
Revises: 7c5c836235d7
Create Date: 2026-07-02 09:51:25.291307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f857908b9499'
down_revision: Union[str, None] = '7c5c836235d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fare_settings', sa.Column('is_truck', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fare_settings', 'is_truck')
    # ### end Alembic commands ###
